### ISSUE TITLE
how to fix this issue in kalilinux 

### ISSUE THREAD

**Issue by TarunV-007** [anmolksachan/CrossInjector#2]
Traceback (most recent call last):
  File "/home/kali/Downloads/CrossInjector/CrossInjector.py", line 178, in <module>
    main()
  File "/home/kali/Downloads/CrossInjector/CrossInjector.py", line 158, in main
    driver = webdriver.Chrome(service=s)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/kali/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x55e84cbcc243 <unknown>
#1 0x55e84c9907a6 <unknown>
#2 0x55e84c9b794a <unknown>
#3 0x55e84c9b549b <unknown>
#4 0x55e84c9f72a7 <unknown>
#5 0x55e84c9f68cf <unknown>
#6 0x55e84c9ede53 <unknown>
#7 0x55e84c9c09ea <unknown>
#8 0x55e84c9c1b2e <unknown>
#9 0x55e84cc20d5e <unknown>
#10 0x55e84cc24a80 <unknown>
#11 0x55e84cc068b0 <unknown>
#12 0x55e84cc25b63 <unknown>
#13 0x55e84cbf7f75 <unknown>
#14 0x55e84cc48998 <unknown>
#15 0x55e84cc48b27 <unknown>
#16 0x55e84cc63c23 <unknown>
#17 0x7fc4a218dfd4 <unknown>

**Comment by anmolksachan** [comment]
Make sure you have chromium browser installed in your machine.
